# Project information
site_name: 'Coil'
site_description: 'An image loading library for Android backed by Kotlin Coroutines'
site_author: '2023 Coil Contributors'
site_url: 'https://coil-kt.github.io/coil/'
remote_branch: gh-pages
edit_uri: ""

# Repository
repo_name: 'Coil'
repo_url: 'https://github.com/coil-kt/coil'

# Copyright
copyright: 'Copyright &copy; 2023 Coil Contributors'

# Configuration
theme:
  name: 'material'
  language: 'en'
  favicon: 'images/coil_logo_black.ico'
  logo: 'images/coil_logo_black.svg'
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/coil-kt/coil'

# Navigation
nav:
  - 'Overview': index.md
  - 'Getting Started': getting_started.md
  - 'Image Loaders': image_loaders.md
  - 'Image Requests': image_requests.md
  - 'Targets': targets.md
  - 'Transformations': transformations.md
  - 'Transitions': transitions.md
  - 'Extending the Image Pipeline': image_pipeline.md
  - 'Java Compatibility': java_compatibility.md
  - 'Jetpack Compose': compose.md
  - 'GIFs': gifs.md
  - 'SVGs': svgs.md
  - 'Video Frames': videos.md
  - 'Testing': testing.md
  - 'Recipes': recipes.md
  - 'FAQ': faq.md
  - 'Migrating from Glide/Picasso': migrating.md
  - 'Upgrading to Coil 2.x': upgrading_to_coil2.md
  - 'Upgrading to Coil 3.x': upgrading_to_coil3.md
  - 'Works with Coil': works_with_coil.md
  - 'API ‚èè': api/index.html
  - 'Change Log': changelog.md
  - 'Contributing': contributing.md
  - 'Code of Conduct': code_of_conduct.md

# CSS
extra_css:
  - 'css/site.css'

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

validation:
  links:
    absolute_links: ignore
  nav:
    omitted_files: ignore

# Built with https://github.com/squidfunk/mkdocs-material
