# Project information
site_name: 'Coil'
site_description: 'An image loading library for Android backed by Kotlin Coroutines'
site_author: '2020 Coil Contributors'
site_url: 'https://coil-kt.github.io/coil/'
remote_branch: gh-pages

# Repository
repo_name: 'Coil'
repo_url: 'https://github.com/coil-kt/coil'

# Copyright
copyright: 'Copyright &copy; 2020 Coil Contributors'

# Configuration
theme:
  name: 'material'
  language: 'en'
  favicon: 'images/coil_logo_black.ico'
  logo: 'images/coil_logo_black.svg'
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/coil-kt/coil'

# Navigation
nav:
  - 'Overview': index.md
  - 'Getting Started': getting_started.md
  - 'Migrating from Glide/Picasso': migrating.md
  - 'Image Loaders': image_loaders.md
  - 'Image Requests': image_requests.md
  - 'Targets': targets.md
  - 'Transformations': transformations.md
  - 'Transitions': transitions.md
  - 'Extending the Image Pipeline': image_pipeline.md
  - 'Java Compatibility': java_compatibility.md
  - 'GIFs': gifs.md
  - 'SVGs': svgs.md
  - 'Video Frames': videos.md
  - 'Recipes': recipes.md
  - 'FAQ': faq.md
  - 'API':
    - 'coil': api/coil-singleton/index.md
    - 'coil-base': api/coil-base/index.md
    - 'coil-gif': api/coil-gif/index.md
    - 'coil-svg': api/coil-svg/index.md
    - 'coil-video': api/coil-video/index.md
  - 'Change Log': changelog.md
  - 'Contributing': contributing.md
  - 'Code of Conduct': code_of_conduct.md

# CSS
extra_css:
  - 'css/site.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
